AWSTemplateFormatVersion: '2010-09-09'
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: VPC-Odoo

  SubnetPublica:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      Tags:
        - Key: Name
          Value: SubxarxaPublica

  SubnetPrivada:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      Tags:
        - Key: Name
          Value: SubxarxaPrivada
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: GW-Odoo

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
   
  EIPNAT:
    Type: AWS::EC2::EIP
    DependsOn: AttachInternetGateway
    Properties:
      Domain: vpc

  NATGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt EIPNAT.AllocationId
      SubnetId: !Ref SubnetPublica
      Tags:
        - Key: Name
          Value: NAT-Odoo

  RouteTablePublica:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: RT-Publica

  RouteInternet:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RouteTablePublica
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  AssociaRutaSubPublica:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SubnetPublica
      RouteTableId: !Ref RouteTablePublica

  RouteTablePrivada:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: RT-Privada

  RoutePrivadaToNAT:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RouteTablePrivada
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NATGateway

  AssociaRutaSubPrivada:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SubnetPrivada
      RouteTableId: !Ref RouteTablePrivada


 
Outputs:
  VPCId:
    Description: "ID de la VPC"
    Value: !Ref VPC
    Export:
      Name: VPCId

  SubnetPublicaId:
    Description: "ID de la Subxarxa Pública"
    Value: !Ref SubnetPublica
    Export:
      Name: SubnetPublicaId

  SubnetPrivadaId:
    Description: "ID de la Subxarxa Privada"
    Value: !Ref SubnetPrivada
    Export:
      Name: SubnetPrivadaId
